info:
  description: Spring Cloud Samples
  url: https://github.com/spring-cloud-samples
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1111/eureka/
spring:
    datasource:
        name: test
        url: jdbc:mysql://task_group_db:33061/nercs
        username: root
        password: cmcc1234
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
      
---
spring:
  profiles: dev
  cloud:
    config:
      uri: https://github.com/immershy/config-repo
oauth2:
  client:
    tokenUri: http://localhost:7001/login/oauth/token
    clientId: test
    clientSecret: test
application:
  domain: ${APPLICATION_DOMAIN:cfapps.io}
endpoints:
  restart: enabled
eureka:
  password: password
  instance:
    hostname: 127.0.0.1
    nonSecurePort: 80
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1112/eureka/
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
---
spring:
  profiles: online
  cloud:
    config:
      uri: http://localhost:7000
endpoints:
  restart: enabled
eureka:
  instance:
    nonSecurePort: 80
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1113/eureka/

