info:
  description: Spring Cloud Config
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1111/eureka/
zuul:
  routes:
    corps:
      path: /corps/**
      #url: http://yq-mod-corp/corps
      serviceId: yq-mod-corp
#redis
redis:
  maxActive: 200
  maxIdle: 100
  minIdle: 10
  maxTotal: 200
  maxWait: 200
  testOnBorrow: false
  testOnReturn: true
  ip: redis_db
  port: 6379
#db
spring:
    datasource:
        name: test
        url: jdbc:mysql://task_group_db:33061/nercs
        username: root
        password: cmcc1234
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
      
---
spring:
  profiles: dev
