spring:
  datasource:
    name: nercs
    url: jdbc:mysql://neas_db:33061/nercs?autoReconnect=true&allowMultiQueries=true
    username: app_common
    password: r|VR^Kmjv(Xw9wTbXGJ6U&?.@
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  mvc:
    staticPathPattern: /yq-mod-caiyin/**

mybatis:
  typeAliasesPackage: com.cmcc.hygcc.web.cy.domain

neas:
  address: neas.eqiwork.com

#咪咕彩印服务
caiyin:
  address: 218.207.208.33:7003
  virtualCorpId: 9990000350
  channelId: 200005830
  enWhiteList: true
