spring:
  datasource:
    name: userstate
    url: jdbc:mysql://localhost:3306/userstate?autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 5
    maxWait: 60000
    minIdle: 10
    removeAbandoned: true
    removeAbandonedTimeout: 1800
    logAbandoned: true
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    
  redis:
    database: 0
    host: localhost
    port: 6379
    timeout: 0
    pool:
      max-active: 300
      max-wait: 50
      max-idle: 500
      min-idle: 0
      
  
neas:
  host: 218.205.115.243:8888
  
